version: "3.7"

services:
    nginx:
        container_name: nginx
        image: nginx:latest
        volumes:
            - ./docker/nginx/config:/etc/nginx/conf.d
        ports: 
            - "80:80"
        depends_on: 
            - app
    app:
        container_name: app
        image: node:latest
        command: bash -c "npm install -g npm@latest && npm install && node /app/bin/www"
        working_dir: /app
        volumes: 
            - .:/app
        ports: 
            - "3000:3000"